# Generated by Django 5.2.6 on 2026-08-12 05:45

import apps.projects.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Loyiha nomi')),
                ('key', models.CharField(help_text='Task raqamlari uchun prefiks, masalan PAY -> PAY-12', max_length=10, verbose_name='Kalit')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('PLANNING', 'Rejalashtirilmoqda'), ('ACTIVE', 'Faol'), ('PAUSED', 'Toxtatilgan'), ('DONE', 'Yakunlangan'), ('ARCHIVED', 'Arxivlangan')], default='ACTIVE', max_length=20, verbose_name='Holat')),
                ('color', models.CharField(default='#0ea5e9', max_length=9, verbose_name='Rang')),
                ('repo_url', models.URLField(blank=True, verbose_name='Repozitoriy (GitHub)')),
                ('docs_url', models.URLField(blank=True, verbose_name='Hujjatlar')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Muddat')),
                ('needed_specialties', models.JSONField(blank=True, default=list, help_text='Loyihaga qaysi yonalish mutaxassislari kerakligi - qidiruvda korsatiladi', verbose_name='Kerakli mutaxassisliklar')),
                ('is_public', models.BooleanField(default=True, help_text='Ochiq bolsa hamma korib, qoshilish sorovi yubora oladi', verbose_name='Ish maydoni ichida ochiq')),
                ('join_code', models.CharField(default=apps.projects.models.make_join_code, max_length=12, unique=True, verbose_name='Qoshilish kodi')),
                ('auto_accept', models.BooleanField(default=False, verbose_name='Sorovlarni avtomatik qabul qilish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Loyiha menejeri')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace', verbose_name='Ish maydoni')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['-updated_at'],
                'unique_together': {('workspace', 'key')},
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Nimalarni qila olasiz, qanday tajribangiz bor', verbose_name='Xabar')),
                ('desired_role', models.CharField(choices=[('MANAGER', 'Loyiha menejeri'), ('DEVELOPER', 'Dasturchi'), ('QA', 'Tester (QA)'), ('VIEWER', 'Kuzatuvchi')], default='DEVELOPER', max_length=20, verbose_name='Istagan rol')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('APPROVED', 'Qabul qilindi'), ('REJECTED', 'Rad etildi'), ('CANCELLED', 'Bekor qilindi')], default='PENDING', max_length=20, verbose_name='Holat')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, verbose_name='Qaror izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='projects.project')),
            ],
            options={
                'verbose_name': 'Qoshilish sorovi',
                'verbose_name_plural': 'Qoshilish sorovlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(blank=True, help_text='Bir-ikki gapda: nima uchun bu loyiha bor', verbose_name='Loyiha maqsadi')),
                ('tech_stack', models.TextField(blank=True, help_text='Django 5, PostgreSQL, Docker, React ...', verbose_name='Texnologiyalar')),
                ('architecture', models.TextField(blank=True, help_text='Papkalar tuzilishi, asosiy modullar, integratsiyalar', verbose_name='Arxitektura')),
                ('setup_steps', models.TextField(blank=True, help_text='docker compose up ... kabi qadamlar', verbose_name='Ishga tushirish')),
                ('conventions', models.TextField(blank=True, help_text='Kod uslubi, branch nomlash, commit qoidalari, PR jarayoni', verbose_name='Kelishuvlar')),
                ('definition_of_done', models.TextField(blank=True, help_text='Har bir task qachon tugagan hisoblanadi', verbose_name="Umumiy 'tayyor' mezoni")),
                ('pitfalls', models.TextField(blank=True, help_text='Avval yol qoyilgan xatolar, tuzoqlar', verbose_name='Ehtiyot boling')),
                ('contacts', models.TextField(blank=True, verbose_name='Kim nima boyicha javob beradi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brief_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loyiha brifi',
                'verbose_name_plural': 'Loyiha briflari',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', 'Loyiha menejeri'), ('DEVELOPER', 'Dasturchi'), ('QA', 'Tester (QA)'), ('VIEWER', 'Kuzatuvchi')], default='DEVELOPER', max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Qoshilgan')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Chiqqan')),
                ('handover_note', models.TextField(blank=True, help_text='Loyihadan chiqishda keyingi dasturchi uchun qoldirilgan izoh', verbose_name='Topshiriq eslatmasi')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_members', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loyiha azosi',
                'verbose_name_plural': 'Loyiha azolari',
                'ordering': ['role', 'joined_at'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
