# Generated by Django 5.2.6 on 2026-08-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(blank=True, help_text='Vazifa raqamlari uchun prefiks (avtomatik yaratiladi)', max_length=10, verbose_name='Kalit'),
        ),
    ]
