# Generated by Django 5.2.6 on 2026-08-14 05:28

import apps.projects.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_deleted_at_project_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versiya'),
        ),
        migrations.CreateModel(
            name='ProjectFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Versiya')),
                ('file', models.FileField(upload_to=apps.projects.models.project_file_version_path, verbose_name='Fayl')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Fayl nomi')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Hajmi (bayt)')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='Turi')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(verbose_name='Yuklangan vaqti')),
                ('replaced_at', models.DateTimeField(auto_now_add=True, verbose_name='Almashtirilgan vaqti')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.projectfile', verbose_name='Hujjat')),
                ('replaced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kim almashtirgan')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_file_versions', to=settings.AUTH_USER_MODEL, verbose_name='Kim yuklagan')),
            ],
            options={
                'verbose_name': 'Hujjatning eski nusxasi',
                'verbose_name_plural': 'Hujjatning eski nusxalari',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['document', '-version'], name='projects_pr_documen_d4f4e2_idx')],
            },
        ),
    ]
