# Generated by Django 5.2.6 on 2026-08-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Tizim ozi tanlaydi - ish maydonidagi loyihalar ajralib tursin', max_length=9, verbose_name='Rang'),
        ),
    ]
