# Generated by Django 5.2.6 on 2026-08-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='desired_role',
            field=models.CharField(choices=[('MANAGER', 'Loyiha menejeri'), ('ADMIN', 'Loyiha admini'), ('DEVELOPER', 'Dasturchi'), ('QA', 'Tester (QA)'), ('VIEWER', 'Kuzatuvchi')], default='DEVELOPER', max_length=20, verbose_name='Istagan rol'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Loyiha menejeri'), ('ADMIN', 'Loyiha admini'), ('DEVELOPER', 'Dasturchi'), ('QA', 'Tester (QA)'), ('VIEWER', 'Kuzatuvchi')], default='DEVELOPER', max_length=20, verbose_name='Rol'),
        ),
    ]
