# Generated by Django 5.2.6 on 2026-08-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectfile_updated_at_projectfile_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDeadlineNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_left', models.PositiveIntegerField(verbose_name='Necha kun qolganda')),
                ('due_date', models.DateField(verbose_name="O'sha paytdagi muddat")),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_notices', to='projects.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Muddat eslatmasi',
                'verbose_name_plural': 'Muddat eslatmalari',
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'days_left', 'due_date'), name='uniq_deadline_notice')],
            },
        ),
    ]
