# Generated by Django 5.2.6 on 2026-08-12 09:31

import apps.projects.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_joinrequest_desired_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.projects.models.project_file_path, verbose_name='Fayl')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Fayl nomi')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Hajmi (bayt)')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='Turi')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loyiha fayli',
                'verbose_name_plural': 'Loyiha fayllari',
                'ordering': ['-created_at'],
            },
        ),
    ]
