# Generated by Django 5.2.6 on 2026-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectfile_deleted_at_projectfile_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hujjat sanasi'),
        ),
        migrations.AddField(
            model_name='projectfileversion',
            name='doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hujjat sanasi'),
        ),
    ]
