# Generated by Django 5.2.6 on 2026-08-18 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectfile_doc_date_projectfileversion_doc_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectbrief',
            name='conventions',
        ),
        migrations.RemoveField(
            model_name='projectbrief',
            name='definition_of_done',
        ),
        migrations.RemoveField(
            model_name='projectbrief',
            name='setup_steps',
        ),
    ]
