# Generated by Django 5.2.6 on 2026-08-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_projectbrief_conventions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='doc_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hujjat sanasi va vaqti'),
        ),
        migrations.AlterField(
            model_name='projectfileversion',
            name='doc_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hujjat sanasi va vaqti'),
        ),
    ]
