# Generated by Django 5.2.6 on 2026-08-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectfile_doc_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_listed',
            field=models.BooleanField(default=False, help_text='Belgilansa loyiha bosh sahifadagi ochiq qidiruvda, royxatdan otmagan odamlarga ham korinadi. Faqat nomi, tavsifi va menejerning ismi chiqadi - azolar, vazifalar va fayllar hech qachon chiqmaydi.', verbose_name='Ochiq qidiruvda korinsin'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Ochiq bolsa ish maydonidagi hamma korib, qoshilish sorovi yubora oladi. Maydondan tashqariga chiqmaydi.', verbose_name='Ish maydoni ichida ochiq'),
        ),
    ]
