# Generated by Django 5.2.6 on 2026-08-13 10:53

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # `replaces` olib tashlandi: almashtirilgan migratsiyalar hamma muhitda
    # qo'llanib bo'lgan va fayllari o'chirilgan (Django hujjatidagi tartib).
    # Endi bu oddiy boshlang'ich migratsiya - papkada bitta chiziq qoladi.

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invite.received', 'Taklif keldi'), ('invite.accepted', 'Taklif qabul qilindi'), ('invite.declined', 'Taklif rad etildi'), ('member.joined', "Yangi a'zo"), ('join.request', "Qo'shilish so'rovi"), ('task.assigned', 'Vazifa biriktirildi'), ('task.review', 'Tekshiruvga tushdi'), ('task.decided', 'Tekshiruv natijasi'), ('task.comment', 'Yangi izoh'), ('chat.message', 'Chat xabari'), ('chat.direct', 'Shaxsiy xabar')], db_index=True, max_length=32, verbose_name='Turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('body', models.CharField(blank=True, max_length=400, verbose_name='Matn')),
                ('url', models.CharField(blank=True, help_text='Interfeys ichidagi manzil, masalan /vazifa/12', max_length=300, verbose_name='Havola')),
                ('meta', apps.core.fields.JSONTextField(blank=True, default=dict, verbose_name="Qo'shimcha")),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name="O'qilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name="Kim sabab bo'ldi")),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Kimga')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
