# Generated by Django 5.2.6 on 2026-08-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('invite.received', 'Taklif keldi'), ('invite.accepted', 'Taklif qabul qilindi'), ('invite.declined', 'Taklif rad etildi'), ('member.joined', "Yangi a'zo"), ('join.request', "Qo'shilish so'rovi"), ('task.assigned', 'Vazifa biriktirildi'), ('task.review', 'Tekshiruvga tushdi'), ('task.decided', 'Tekshiruv natijasi'), ('task.comment', 'Yangi izoh'), ('chat.message', 'Chat xabari'), ('chat.direct', 'Shaxsiy xabar')], db_index=True, max_length=32, verbose_name='Turi'),
        ),
    ]
