# Generated by Django 5.2.6 on 2026-08-13 09:09

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='meta',
            field=apps.core.fields.JSONTextField(blank=True, default=dict, verbose_name="Qo'shimcha"),
        ),
    ]
