# Generated by Django 5.2.6 on 2026-08-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('task.assigned', 'Vazifa biriktirildi'), ('task.reassigned', "Vazifa o'tkazildi"), ('task.review', 'Tekshiruvga tushdi'), ('task.decided', 'Tekshiruv natijasi'), ('task.comment', 'Yangi izoh'), ('chat.message', 'Chat xabari'), ('chat.direct', 'Shaxsiy xabar'), ('join.request', "Qo'shilish so'rovi"), ('project.deadline', 'Loyiha muddati yaqin')], db_index=True, max_length=32, verbose_name='Turi'),
        ),
    ]
