# Generated by Django 5.2.6 on 2026-08-12 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_color'),
        ('workspaces', '0002_alter_workspace_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, verbose_name='Taklif qilinayotgan rol')),
                ('message', models.TextField(blank=True, help_text='Nima uchun taklif qilinayotgani', verbose_name='Xabar')),
                ('status', models.CharField(choices=[('PENDING', 'Javob kutilmoqda'), ('ACCEPTED', 'Qabul qilindi'), ('DECLINED', 'Rad etildi'), ('CANCELLED', 'Bekor qilindi')], db_index=True, default='PENDING', max_length=20, verbose_name='Holat')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Javob vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Kim taklif qildi')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.project', verbose_name='Loyiha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='Kimga')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='workspaces.workspace', verbose_name='Ish maydoni')),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='invites_inv_user_id_199221_idx')],
            },
        ),
    ]
