# Generated by Django 5.2.6 on 2026-08-12 05:45

import apps.accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.Sh.')),
                ('job_title', models.CharField(blank=True, help_text='Masalan: Backend dasturchi', max_length=100, verbose_name='Lavozim')),
                ('global_role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Loyiha menejeri'), ('DEVELOPER', 'Dasturchi')], default='DEVELOPER', max_length=20, verbose_name='Tizim roli')),
                ('specialty', models.CharField(choices=[('BACKEND', 'Backend dasturchi'), ('FRONTEND', 'Frontend dasturchi'), ('FULLSTACK', 'Fullstack dasturchi'), ('MOBILE', 'Mobil dasturchi'), ('DEVOPS', 'DevOps muhandisi'), ('QA', 'Tester (QA)'), ('DESIGNER', 'UI/UX dizayner'), ('DATA', 'Data / ML muhandisi'), ('ANALYST', 'Biznes tahlilchi'), ('SECURITY', 'Xavfsizlik mutaxassisi'), ('PM', 'Loyiha menejeri')], default='BACKEND', help_text='Royxatdan otishda tanlanadi va vazifa taqsimotiga tasir qiladi', max_length=20, verbose_name='Mutaxassislik')),
                ('seniority', models.CharField(choices=[('INTERN', 'Stajyor'), ('JUNIOR', 'Junior'), ('MIDDLE', 'Middle'), ('SENIOR', 'Senior'), ('LEAD', 'Lead / Arxitektor')], default='JUNIOR', max_length=20, verbose_name='Daraja')),
                ('years_experience', models.PositiveSmallIntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('bio', models.TextField(blank=True, verbose_name="Qisqacha ma'lumot")),
                ('skills', models.CharField(blank=True, help_text='Vergul bilan: Python, Django, React', max_length=255, verbose_name="Ko'nikmalar")),
                ('github_username', models.CharField(blank=True, max_length=80, verbose_name='GitHub username')),
                ('telegram', models.CharField(blank=True, max_length=80, verbose_name='Telegram')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Xodim (django-admin)')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Ro'yxatdan o'tgan")),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
