# Generated by Django 5.2.6 on 2026-08-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_github_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='global_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BOSS', 'Boshliq'), ('MANAGER', 'Loyiha menejeri'), ('DEVELOPER', 'Dasturchi')], default='DEVELOPER', max_length=20, verbose_name='Tizim roli'),
        ),
    ]
