# Generated by Django 5.2.6 on 2026-08-13 10:53

import apps.tasks.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tasks', '0001_initial'), ('tasks', '0002_attachment'), ('tasks', '0003_submission_attachment_submission_submissionedit_and_more'), ('tasks', '0004_alter_task_due_date')]

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nomi')),
                ('color', models.CharField(default='#64748b', max_length=9, verbose_name='Rang')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='projects.project')),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, editable=False, verbose_name='Raqam')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Nima qilish kerak')),
                ('acceptance_criteria', models.TextField(blank=True, help_text='Aniq royxat: nima ishlasa task qabul qilinadi. Chalkashlikni shu yopadi.', verbose_name='Tayyor deb hisoblash mezoni')),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'Bajarilishi kerak'), ('IN_PROGRESS', 'Jarayonda'), ('IN_REVIEW', 'Tekshiruvda'), ('CHANGES_REQUESTED', 'Tuzatish kerak'), ('BLOCKED', 'Toxtab qolgan'), ('DONE', 'Bajarildi'), ('CANCELLED', 'Bekor qilindi')], db_index=True, default='TODO', max_length=20, verbose_name='Holat')),
                ('priority', models.IntegerField(choices=[(1, 'Past'), (2, 'Ortacha'), (3, 'Yuqori'), (4, 'Shoshilinch')], default=2, verbose_name='Muhimlik')),
                ('task_type', models.CharField(choices=[('FEATURE', 'Yangi funksiya'), ('BUG', 'Xatolik'), ('CHORE', 'Texnik ish'), ('DOCS', 'Hujjat'), ('RESEARCH', 'Tadqiqot')], default='FEATURE', max_length=20, verbose_name='Turi')),
                ('required_specialty', models.CharField(blank=True, help_text='Belgilansa, vazifa faqat shu yonalishdagi azolarga taklif qilinadi', max_length=20, verbose_name='Kerakli mutaxassislik')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Muddat')),
                ('estimate_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Rejalashtirilgan soat')),
                ('branch_name', models.CharField(blank=True, max_length=120, verbose_name='Branch')),
                ('pr_url', models.URLField(blank=True, verbose_name='Pull request')),
                ('blocked_reason', models.CharField(blank=True, max_length=250, verbose_name='Nega toxtab qolgan')),
                ('position', models.IntegerField(default=0, verbose_name='Tartib')),
                ('review_round', models.PositiveSmallIntegerField(default=0, verbose_name='Tekshiruv aylanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Tekshiruvga yuborilgan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, related_name='tasks', to='tasks.label', verbose_name='Teglar')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='Asosiy task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Tekshiruvchi')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['position', '-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('APPROVED', 'Qabul qilindi'), ('CHANGES_REQUESTED', 'Tuzatish talab qilindi'), ('REJECTED', 'Rad etildi')], max_length=25, verbose_name='Qaror')),
                ('comment', models.TextField(blank=True, help_text='Nimani tuzatish kerak - aniq yozing', verbose_name='Izoh')),
                ('round_no', models.PositiveSmallIntegerField(default=1, verbose_name='Aylana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Tekshiruv',
                'verbose_name_plural': 'Tekshiruvlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biriktirish',
                'verbose_name_plural': 'Biriktirishlar',
                'ordering': ['assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Sarflangan soat')),
                ('note', models.TextField(help_text='Qaysi fayl, qanday yechim, nimaga shunday qilindi', verbose_name='Nima qilindi')),
                ('work_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ish jurnali',
                'verbose_name_plural': 'Ish jurnallari',
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='tasks_task_project_b78682_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', '-priority'], name='tasks_task_status_314078_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'user')},
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(default=1, verbose_name='Tekshiruv aylanasi')),
                ('text', models.TextField(help_text="Nima qilindi, qaysi fayllar o'zgardi, nimaga e'tibor berish kerak", verbose_name='Qilingan ish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_count', models.PositiveIntegerField(default=0, verbose_name='Necha marta tahrirlangan')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Kim topshirdi')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.task')),
            ],
            options={
                'verbose_name': "Ish topshirig'i",
                'verbose_name_plural': 'Ish topshiriqlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.tasks.models.attachment_path, verbose_name='Fayl')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Fayl nomi')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Hajmi (bayt)')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='Turi')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.submission', verbose_name='Topshiriq')),
            ],
            options={
                'verbose_name': 'Biriktirilgan fayl',
                'verbose_name_plural': 'Biriktirilgan fayllar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_text', models.TextField(verbose_name='Eski matn')),
                ('new_text', models.TextField(verbose_name='Yangi matn')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_edits', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='tasks.submission')),
            ],
            options={
                'verbose_name': 'Topshiriq tahriri',
                'verbose_name_plural': 'Topshiriq tahrirlari',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['task', '-created_at'], name='tasks_submi_task_id_176546_idx'),
        ),
    ]
