# Generated by Django 5.2.6 on 2026-08-12 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(default=1, verbose_name='Tekshiruv aylanasi')),
                ('text', models.TextField(help_text="Nima qilindi, qaysi fayllar o'zgardi, nimaga e'tibor berish kerak", verbose_name='Qilingan ish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_count', models.PositiveIntegerField(default=0, verbose_name='Necha marta tahrirlangan')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Kim topshirdi')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.task')),
            ],
            options={
                'verbose_name': "Ish topshirig'i",
                'verbose_name_plural': 'Ish topshiriqlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.submission', verbose_name='Topshiriq'),
        ),
        migrations.CreateModel(
            name='SubmissionEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_text', models.TextField(verbose_name='Eski matn')),
                ('new_text', models.TextField(verbose_name='Yangi matn')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_edits', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='tasks.submission')),
            ],
            options={
                'verbose_name': 'Topshiriq tahriri',
                'verbose_name_plural': 'Topshiriq tahrirlari',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['task', '-created_at'], name='tasks_submi_task_id_176546_idx'),
        ),
    ]
