# Generated by Django 5.2.6 on 2026-08-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_attachment_deleted_at_attachment_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'Nazoratda'), ('IN_PROGRESS', 'Jarayonda'), ('IN_REVIEW', 'Tekshiruvda'), ('CHANGES_REQUESTED', 'Tuzatish kerak'), ('BLOCKED', 'Toxtab qolgan'), ('DONE', 'Bajarildi'), ('CANCELLED', 'Bekor qilindi')], db_index=True, default='TODO', max_length=20, verbose_name='Holat'),
        ),
    ]
