# Generated by Django 5.2.6 on 2026-08-12 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(db_index=True, max_length=50, verbose_name='Amal')),
                ('summary', models.CharField(max_length=300, verbose_name='Qisqacha')),
                ('detail', models.TextField(blank=True, verbose_name='Batafsil')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Qoshimcha')),
                ('target_label', models.CharField(blank=True, max_length=200, verbose_name='Obyekt')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tasks.task')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Tarix yozuvi',
                'verbose_name_plural': 'Loyiha tarixi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='activity_ac_project_0d9dc1_idx'), models.Index(fields=['actor', '-created_at'], name='activity_ac_actor_i_200108_idx'), models.Index(fields=['task', '-created_at'], name='activity_ac_task_id_7a5790_idx')],
            },
        ),
    ]
