# Generated by Django 5.2.6 on 2026-08-13 09:09

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='meta',
            field=apps.core.fields.JSONTextField(blank=True, default=dict, verbose_name='Qoshimcha'),
        ),
    ]
