# Generated by Django 5.2.6 on 2026-08-13 10:52

import apps.workspaces.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('workspaces', '0001_initial'), ('workspaces', '0002_alter_workspace_color')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Manzil')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('color', models.CharField(blank=True, default='', help_text='Tizim ozi tanlaydi - maydonlar royxatda ajralib tursin', max_length=9, verbose_name='Rang')),
                ('join_code', models.CharField(default=apps.workspaces.models.make_code, max_length=12, unique=True, verbose_name='Taklif kodi')),
                ('is_open', models.BooleanField(default=True, verbose_name='Ochiq (kod bilan qoshilsa boladi)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Ish maydoni',
                'verbose_name_plural': 'Ish maydonlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Egasi'), ('ADMIN', 'Administrator'), ('MEMBER', 'Azo')], default='MEMBER', max_length=20, verbose_name='Rol')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Ish maydoni azosi',
                'verbose_name_plural': 'Ish maydoni azolari',
                'ordering': ['role', 'joined_at'],
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
