# Generated by Django 5.2.6 on 2026-08-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Tizim ozi tanlaydi - maydonlar royxatda ajralib tursin', max_length=9, verbose_name='Rang'),
        ),
    ]
