# Generated by Django 5.2.6 on 2026-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_deleted_at_workspace_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Ochiq (royxatda korinadi, kod bilan qoshiladi)'),
        ),
    ]
