# Generated by Django 5.2.6 on 2026-08-18 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Chat raqami')),
                ('is_muted', models.BooleanField(default=False, verbose_name="Xabarlar o'chirilgan")),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name="Bog'langan vaqt")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Telegram bog'lanish",
                'verbose_name_plural': "Telegram bog'lanishlar",
            },
        ),
    ]
