# Generated by Django 5.2.6 on 2026-08-12 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('projects', '0003_alter_project_color'),
        ('workspaces', '0002_alter_workspace_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to=settings.AUTH_USER_MODEL, verbose_name='Kimga (shaxsiy)'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['recipient', '-created_at'], name='chat_chatme_recipie_c56b14_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['author', '-created_at'], name='chat_chatme_author__731b81_idx'),
        ),
    ]
