# Generated by Django 5.2.6 on 2026-08-20 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Taklif matni')),
                ('scope', models.CharField(choices=[('OPEN', 'Ochiq'), ('CLOSED', 'Yopiq')], db_index=True, default='OPEN', max_length=10, verbose_name='Turi')),
                ('is_anonymous', models.BooleanField(default=False, help_text="Muallif hech kimga ko'rsatilmaydi", verbose_name='Anonim')),
                ('status', models.CharField(choices=[('PENDING', "Ko'rib chiqilmoqda"), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], db_index=True, default='PENDING', max_length=10, verbose_name='Holat')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Qaror vaqti')),
                ('decision_note', models.TextField(blank=True, verbose_name='Boshliq izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Qaror qilgan')),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('FOR', "Qo'shilaman"), ('AGAINST', "Qo'shilmayman"), ('NEUTRAL', 'Betarafman')], max_length=10, verbose_name='Tanlov')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='suggestions.suggestion', verbose_name='Taklif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_votes', to=settings.AUTH_USER_MODEL, verbose_name='Kim')),
            ],
            options={
                'verbose_name': 'Taklif ovozi',
                'verbose_name_plural': 'Taklif ovozlari',
            },
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['scope', '-created_at'], name='suggestions_scope_2f8759_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestion',
            index=models.Index(fields=['author', '-created_at'], name='suggestions_author__70da43_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestionvote',
            index=models.Index(fields=['suggestion', 'choice'], name='suggestions_suggest_7b0f36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='suggestionvote',
            unique_together={('suggestion', 'user')},
        ),
    ]
