# Generated by Django 5.2.6 on 2026-08-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UiText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, unique=True, verbose_name='Kalit')),
                ('value', models.TextField(verbose_name='Matn')),
                ('group', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Guruh')),
                ('note', models.CharField(blank=True, help_text='Bu matn qayerda chiqadi', max_length=250, verbose_name='Izoh')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
            ],
            options={
                'verbose_name': 'Interfeys matni',
                'verbose_name_plural': 'Interfeys matnlari',
                'ordering': ('group', 'key'),
            },
        ),
    ]
